### ISSUE TITLE
Getting a runtime error when there is no NVIDIA GPU

### ISSUE THREAD

**Issue by sidu21** [nmhaddad/Fast-Track#7]
The console stream is logged into /home/user/sg_logs/console.log
[2023-05-09 17:22:15] INFO - crash_tips_setup.py - Crash tips is enabled. You can set your environment variable to CRASH_HANDLER=FALSE to disable it
[2023-05-09 17:22:17] WARNING - __init__.py - Failed to import pytorch_quantization
[2023-05-09 17:22:17] WARNING - calibrator.py - Failed to import pytorch_quantization
[2023-05-09 17:22:17] WARNING - export.py - Failed to import pytorch_quantization
[2023-05-09 17:22:17] WARNING - selective_quantization_utils.py - Failed to import pytorch_quantization
[2023-05-09 17:22:18] INFO - checkpoint_utils.py - License Notification: YOLO-NAS pre-trained weights are subjected to the specific license terms and conditions detailed in 
https://github.com/Deci-AI/super-gradients/blob/master/LICENSE.YOLONAS.md
By downloading the pre-trained weight files you agree to comply with these terms.
Traceback (most recent call last):
  File "example_fasttrack.py", line 14, in <module>
    detector = YOLONAS(**config['detector'], names=config['names'], image_shape=(camera.get(3), camera.get(4)))
  File "/home/user/Fast-Track/fast_track/object_detection/third_party/yolo_nas/yolo_nas.py", line 34, in __init__
    self.model = super_gradients.training.models.get(self.weights_path, pretrained_weights=pretrained).cuda()
  File "/home/user/fasttrack/lib/python3.8/site-packages/torch/nn/modules/module.py", line 905, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/user/fasttrack/lib/python3.8/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/home/user/fasttrack/lib/python3.8/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/home/user/fasttrack/lib/python3.8/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  [Previous line repeated 2 more times]
  File "/home/user/fasttrack/lib/python3.8/site-packages/torch/nn/modules/module.py", line 820, in _apply
    param_applied = fn(param)
  File "/home/user/fasttrack/lib/python3.8/site-packages/torch/nn/modules/module.py", line 905, in <lambda>
    return self._apply(lambda t: t.cuda(device))
  File "/home/user/fasttrack/lib/python3.8/site-packages/torch/cuda/__init__.py", line 247, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

**Comment by nmhaddad** [comment]
Thanks for letting me know. #8 fixes this problem. Should be all set now!

**Comment by sidu21** [comment]
Thank you!
